# fly.toml app configuration file generated for blue-chip on 2026-05-30T04:17:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blue-chip'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[processes]
  app = 'node src/index.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
